name: PHP Laravel CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, intl
          coverage: xdebug
          tools: php-cs-fixer, phpunit

      - name: Install dependencies
        run: ls -al && ls .. -al

      - name: Test
        run: php artisan test
